### PR TITLE
Support for going to previous/next media in a series

### PR DESCRIPTION
**Pull request by yhorowitz**
Addresses Issue #100 

- Made PlayerRoute a Stateful Widget so that there shouldn't be a weird jump when switching media (that happens when a new route is pushed)
- Will only go to the previous media if its within the first 10 seconds of the current media. Otherwise it goes back to the beginning.
- The functionality isn't supported from the current media bar (when not in the MediaRoute
- Moved the getParent function to the Media class itself

### CODE REVIEW

**Comment by yringler** [comment]
> so that there shouldn't be a weird jump

What jump were you seeing? What if the route change wouldn't have any animation? What if we used keys here, to reuse UI widgets which didn't change? Maybe a nested router?

I don't like the idea of the router not knowing where user is in the app.

**Comment by yringler** [comment]
IMO "a different class" is conceptually a different route, and should be implemented as such, which would also clear up some other code issues.
An appropriate transition animation (or none; I can't complain, I have zero experiance with flutter animation, but a nice animation is always nice) is probably a good idea.

**Comment by yhorowitz** [comment]
Ok, I'll switch it to switch routes and leave making the transition smoother for a future date

**Comment by yhorowitz** [comment]
@yringler I made the change to switch routes (and converted it back to a stateless widget.

It still doesn't work with the global audio bar since it only has the media_source uri passed in and not the media itself.

Also, the previous isn't working properly but this seems to be because there something wrong with it updating the current duration played. The progress bar isn't updating either. This doesn't seem to be caused by the changes I made.

**Comment by yringler** [comment]
> It still doesn't work with the global audio bar since it only has the media_source uri passed in and not the media itself. Is there a way to get the media object from the uri?

No, not yet
We could add a findBySource method to data layer.
Or, the existing media method could search by URI if it can't find the ID

But the whole thing should be moot; the audio_handler needs to be updated to use the real media ID, then the global_audio_bar will have the real media ID, then we can always query it directly.
In the meantime, I don't think it's terrible to take the most recent class and use that to find parents (asuming that the source matches)

>  the current duration played. The progress bar isn't updating either. 

The apps duration handling isn't the best.
All media items should have duration saved with them - maybe make sure that usages of duration come from a stream, so that it'll get updates.
I think now it gets the duration once (Future) and goes with it.

**Comment by yringler** [comment]
Replaced with #117

**Pull request closed without merging**
